[params.author]
name = "Gianluigi Dal Toso"
image = "img/author.jpg"
headline = "Security Engineer & Software Developer"
bio = "Brazilian computer engineer (ITA) working in offensive security. Building things with Go. Breaking things for a living."
links = [
  { github = "https://github.com/gitoso" },
  { linkedin = "https://www.linkedin.com/in/gianluigi-toso/" },
]
